style"paned"{
GtkPaned::handle-size=10
bg[NORMAL]=shade(0.75,@bg_color)
bg[PRELIGHT]=shade(0.75,@bg_color)
bg[SELECTED]=shade(0.75,@bg_color)
bg[ACTIVE]=shade(0.75,@bg_color)
bg[INSENSITIVE]=@bg_color
engine"pixmap"{
image{
function=HANDLE
detail="paned"
orientation=VERTICAL
overlay_file="images/hpaned.png"
overlay_stretch=TRUE
overlay_border={4,0,0,0}}
image{
function=HANDLE
detail="paned"
orientation=HORIZONTAL
overlay_file="images/vpaned.png"
overlay_stretch=TRUE
overlay_border={0,0,4,0}}}}
class"GtkPaned"style"paned"

