style"scale_pixmap"{
xthickness=2
ythickness=2
GtkScale::slider-length=34
GtkScale::value-spacing=1
GtkRange::trough-border=1
GtkRange::stepper-size=28
GtkRange::activate-slider=0
GTKScale::slider-width=28
engine"pixmap"{
image{
function=BOX
detail="trough"
orientation=HORIZONTAL
file="images/scalehtrough.png"
border={10,8,12,12}
stretch=TRUE}
image{
function=SLIDER
orientation=HORIZONTAL
file="images/scalehslider.xpm"
border={2,2,8,8}
stretch=TRUE}
image{
function=BOX
detail="trough"
orientation=VERTICAL
file="images/scalevtrough.png"
border={12,12,8,8}
stretch=TRUE}
image{
function=SLIDER
orientation=VERTICAL
file="images/scalevslider.xpm"
border={8,12,2,2}
stretch=TRUE}}}
class"GtkScale"style"scale_pixmap"
